# Linter Options
options:
    merge-default-rules: false
    formatter: stylish

# Rule Configuration
rules:
    extends-before-mixins: 2
    extends-before-declarations: 2
    placeholder-in-extend: 0
    mixins-before-declarations:
        - 0
        -
            exclude:
                - breakpoint
                - mq
    no-warn: 1
    no-debug: 1
    no-ids: 2
    no-important: 2
    hex-notation:
        - 2
        -
            style: lowercase
    indentation:
       - 4
       -
           size: 4
    variable-for-property:
        - 2
